# Generated by Django 5.1.4 on 2025-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, null=True)),
                ('movie_description', models.TextField(max_length=200)),
                ('movie_age_restriction', models.CharField(choices=[('E', 'Everyone'), ('PG', 'Parental Guidance'), ('PG13+', 'Parental Guidance 13+'), ('18+', 'Adults 18+')], default='E', max_length=30)),
                ('movie_genre', models.CharField(choices=[('Action', 'Action'), ('Anime', 'Award-Warning'), ('Award-Winning', 'Award-Wanning'), ('Classics', 'Classics'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentaries', 'Documentaries'), ('Dramas', 'Dramas'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Kids', 'Kids'), ('Family', 'Family'), ('Musicals', 'Musicals'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Sports', 'Sports'), ('Stand-Up', 'Stand-Up'), ('Thriller', 'Thriller')], default='Action', max_length=30)),
                ('movie_poster', models.ImageField(upload_to='movies/posters')),
                ('movie_logo', models.ImageField(upload_to='movies/logos')),
                ('movie_trailer', models.FileField(upload_to='movies/trailers')),
            ],
        ),
    ]
