# Generated by Django 5.1.4 on 2025-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_app', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.ImageField(null=True, upload_to='movies/logos'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(null=True, upload_to='movies/posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.FileField(null=True, upload_to='movies/trailers'),
        ),
    ]
