# Generated by Django 5.1.4 on 2025-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_app', '0003_alter_movie_movie_logo_alter_movie_movie_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.ImageField(null=True, upload_to='media/movies/logos'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(null=True, upload_to='media/movies/posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.FileField(null=True, upload_to='media/movies/trailers'),
        ),
    ]
